### ISSUE TITLE
Question about task_dialog

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#14]
Hi, can you explain all the functions for task_dialog?
![taskdialog_task](https://user-images.githubusercontent.com/7018625/29166349-9864388e-7df8-11e7-9a9d-baa5e5350fcc.jpg)
I not so sure the use of Depends To, Resources and Responsible.

**Comment by eoyilmaz** [comment]
You can create/update ``Task`` instances by using the ``Task Dialog``.

The ``Depends To`` field is for specifying inter task dependencies which means that you can create a ``Task`` dependency chain where you can define which ``Task`` should start before a particular ``Task``. It is used for scheduling the Project.

For example you can create a ``Model`` task and then a ``Rig`` task which depends to the ``Model`` task. So when you schedule the ``Project`` (by using the ``TaskJugglerScheduler.schedule()`` method or ``Studio.schedule()`` method, --no UI for them for now--) Stalker will set the ``Task.start`` and ``Task.end`` dates so that the ``Rig.start`` is equal to ``Model.end`` (if conditions are suitable for that, meaning that the assigned resource for that task has an empty time slot that he/she can work on that task... pretty cumbersome I know but you can read the TaskJuggler Documentation for details at: http://taskjuggler.org/ ).

The ``Resources`` field is for defining the ``User`` that will work on that particular ``Task``. This is again used both for project management and also to show each ``User`` which ``Task`` they have to work on. You can define multiple resources for a task.

The ``Responsible`` field is for defining a ``Responsible`` for a particular ``Task``. It is the ``Responsible``s duty to approve that task or give revision to. When the user requests a review a ``Review`` instance is created and assigned to the ``Responsible``. Then the ``Responsible`` approves the task or request a revision, then Stalker sets the ``Status`` of that ``Task`` accordingly. Also if the ``Responsible`` field is empty it is inherited from the parent ``Task`` unless it is a ``root task`` which means that it doesn't have a parent, if this is the case you need to enter a responsible. You can define multiple responsible for a task, then each responsible reviews the task separately and according to their decisions that task is either set to ``Complete (CMPL)`` or ``Has Revision (HREV)`` statuses.

All of these things are much more meaningful when you use them with ``Stalker_Pyramid``. Unfortunately the ``Stalker_Pyramid`` (at least the OpenSource one) is still in development.

**Comment by tws0002** [comment]
Thanks for the explanation. 
Can wait to get `Stalker_Pyramid ` a test!! seems very helpful tools for studio management system.
when do you think we can try `Stalker_Pyramid `?

**Comment by eoyilmaz** [comment]
Currently I'm reading a book about Angular 2/4 and I'm half finished. So it will take at least 1 more month before having anything at hand...

**Comment by tws0002** [comment]
Hey just wondering how's the stalker pyramid going on? Anything to share with us yet? Really hope can test on stalker pyramid.

**Comment by eoyilmaz** [comment]
Not going very well. But I started to develop a Qt version (the ``ui/project_manager.py``) instead of dealing with JavaScript and HTML.
