### ISSUE TITLE
Python Communication with adobe product!

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#19]
Hi Eoyilmaz,

I doing some research about how Python communicates with Adobe product!! here is some result I have so far. Do you want to have a look on it? here is the link: 
https://gist.github.com/tws0002/0c2496781dbf3feced906f1ef602ea59

which I think is better than using comtypes. correct me if im wrong!! 

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
Not it's not better. This way you constant need to parse results from the network socket. comtypes handles that already for you and it is much easier to work with.

**Comment by tws0002** [comment]
ic. 

but after effect seems don't support comtypes!!

**Comment by eoyilmaz** [comment]
Strange if it supports socket it should also support comtypes.

**Comment by tws0002** [comment]
I have been tried for so many times !! but no luck on it!! 
here is some error from internet 
http://tech-artists.org/t/python-photoshop/150/41

Desmond

**Comment by tws0002** [comment]
Hi do u have any idea on this problem?

**Comment by eoyilmaz** [comment]
I've tested if my implementation is still working for Photoshop CC 2018 and you know what, it is working without any problems (though I had to call the script form a command prompt, just because I don't have the ANIMA_PATH env variable set to the correct path).

So I believe this by itself is a proof of concept that ``comtypes`` library is enough to work with Adobe products.

**Comment by tws0002** [comment]
Maybe I will get some test on after effect!! Do you mind to give some instruction guideline, if I wanna port after effect to anima pipeline?
