### ISSUE TITLE
Hey, can you explain about the new 3dsmax workflow for anima?

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#21]
Hey, do u mind to give some explanation about 3ds max workflow for anima?

**Comment by eoyilmaz** [comment]
There is no workflow yet.

I've created the necessary code to open & save the scene (and thus create a project structure, set the render resolution and scene frame rate etc.) with the regular Version Creator UI.

And lately I've been working on a code that automatically converts the scene from VRay to RedShift (anima.env.max.vray2rs). For now the code can successfully convert material nodes such as: VRayMtl, VrayBlendMtl, VRayColor, VRayDirt, VRayLightMtl and the Normal Bump node of 3ds Max to their RedShift counterparts. Seeing the same render done in minutes rather than hours is fun :)

I plan to add XRef support. So the user should be able to create rederences and track them as we do in Maya.

That's all.

**Comment by tws0002** [comment]
Thanks for the explanation.

Question
-How to setup anima environment in max?
-How to execute version_creator() in max?

**Comment by eoyilmaz** [comment]
If you're able to run ``version_creator`` in Maya, then you do not need to do anything. Just open the MAXScriptListener select Python and run the following code:

```python
from anima.ui.scripts import max
max.version_creator()
```

If it complains about that it can not find ``anima`` than add the path of the ``anima`` library to your ``PYTHONPATH`` envrionment variable. But as I've said, if you're able to run it in Maya than it should run in Max without any further adjustment.
