### ISSUE TITLE
How can I create Projects and Tasks for anima?

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#6]
Hi Erkan's, 

How can I create Projects and Tasks for anima?
I don't know how to create a database to store all the user, task, project and etc in a database!!
can u please give me some idea to create a data for user login, project and task.
how can I manage my folder structure? 
Is anima ready for nuke ,houdini and photoshop? 
I'm new in doing studio pipeline!! 

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
Yes it can. Creating your first Project is a little bit daunting, but when
you finish setting it up, consequent projects are easy to setup, and it is
much much better if you build your own GUI around it.

Did you follow the tutorial here (I don't know if it is up to date by the
way):

https://www.pythonhosted.org/stalker/index.html


It doesn't explain how to create a database, but it is easy: just download
PoatgreSQL and install it (if you are under Linux then use your
distributions own package manager to download and install it). Then create
a user in the database for yourself (ex: stalker_admin) and give it a
password (ex:stalker). And then create a database in it with the name
"stalker". (You need to search for things like "how to create a user in
Posetgresql" and "how to create a database in Postgresql").

And then install Psycopg2, Sqlalchemy, Jinja2, Pytz and then Stalker to
reach the database from your favorite Python version (I think you've
already done these steps).

Then in Python shell run:

```python
from stalker import db
db.setup({
    'sqlalchemy.url': 'postgresql://stalker_admin:stalker@localhost/stalker'
})
db.init()
```

Stalker will create the necessary tables in it.

The you can use the commands that you've learned from the tutorial.

That's it.

Creating a PySide GUI is a better way of using Stalker and Anima then
writing Python code for daily project management.

On Mar 28, 2017 7:21 PM, "Desmond" <notifications@github.com> wrote:

Hi Erkan's,

How can I create Projects and Tasks for anima?
I don't know how to create a database to store all the user, task, project
and etc in a database!!
can u please give me some idea to create a data for user login, project and
task.
how can I manage my folder structure?
Is anima ready for nuke ,houdini and photoshop?
I'm new in doing studio pipeline!!

Thanks
Desmond

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eoyilmaz/anima/issues/6>, or mute the thread

**Comment by eoyilmaz** [comment]
I think you are running psycopg2 installed for Linux under Windows. Don't
do that. Install psycopg2 locally.

Erkan Ozgur Yilmaz
